### ISSUE TITLE
Implement plugin development environment support for linux

### ISSUE THREAD

**Issue by Stehfyn** [notgull/pictonode#36]
As of now, there only exists support for plugin development on windows which includes:
* Plugin Install script
* GIMP GI Typelib Sandbox environment script

GIMP 2.99 Development branch installs via flatpak and as such presents some obstacles for reaching parity with windows as far as setting up a workflow

Issues to solve:

### Plugin Install:
- [x] ~~Adding plugin folder to GIMP's plugin folder search paths (Needs to be done manually until workaround is created)~~ #43
- [x] ~~Installing .typelib/.so dependencies alongside GIMP's default typelibs (Could be done multiple ways)~~ #43

### Plugin Sandbox:
- [x] ~~Setting up environment variables for GObject Introspection in sandbox environment (Find default paths)~~ #45 #46

**Comment by notgull** [comment]
I don't think it would be that hard to set up a Python script to download GIMP and build it from source. I think that might take care of at least *some* of these issues.

**Comment by Stehfyn** [comment]
I think that could help as far as bootstrapping us into getting a dev environment for the plugin for the time being if it's intuitive to get the gtknodes typelib/.so dependency going in it. It would be ideal to figure a way to work with flatpak as it is the promoted form of distribution for GIMP.

There's two issues @parkern342 and I have run into with the flatpak installation of gimp. 

1. One must be running flatpak as superuser/root for our installed plugin to properly load. To test:
From `pictonode/gimp/pictonode-gimp-plugin/GIMP\ 2.99` we can install our plugin to the gimp flatpak install via
```bash
cp -r ./pictonode ~/.var/app/org.gimp.GIMP/config/GIMP/2.99/plug-ins
chmod -R 777 ~/.var/app/org.gimp.GIMP/config/GIMP/2.99/plug-ins/pictonode
```
but to actually have the plugin work we have to
```bash
sudo -s
```
before
```bash
flatpak run org.gimp.GIMP//beta
```

2. We're still looking for how the gtknode .typelib/.so needs to be placed within whatever directories to get runtime access in our plugin via
```python
import gi
gi.require_version("GtkNodes", "0.1")
from gi.repository import GtkNodes
```
GIMP's Windows directory structure is all self-contained and thus relatively straightforward, however the flatpak install appears be using directories from all over.

We think the path for the .typelib/.so is `/var/lib/flatpak/app/org.gimp.GIMP/{arch}/beta/{some long hash}/files/lib`. Parker's been attempting to figure this one out and unsure of what he has tried.

**Comment by notgull** [comment]
Ah, I see.

> One must be running flatpak as superuser/root for our installed plugin to properly load.

To me this smells like "flatpak runs everything as an external user that doesn't have permissions to run the `.so` file". If the file permissions are `chmod 777`, does that fix anything? Obviously not a viable prod solution, but it might let us narrow down the issue.

> We're still looking for how the gtknode .typelib/.so needs to be placed within whatever directories to get runtime access in our plugin

Is it feasible to do a manual override for this? As in, could we set `GI_TYPELIB_PATH` and `LD_LIBRARY_PATH` before loading `gi` in our environment? This seemed to work on my end.

**Comment by Stehfyn** [comment]
> To me this smells like "flatpak runs everything as an external user that doesn't have permissions to run the `.so` file". If the file permissions on the `typelib` and `so` are `chmod 777`, does that fix anything? Obviously not a viable prod solution, but it might let us narrow down the issue.
> 
After some testing it seems that you're right, and it seems to be why popular GIMP plugins are supported "[flatpak extensions](https://www.gimp.org/news/2020/10/07/gimp-2-10-22-released/#plug-ins-and-manuals-in-flatpak-gimp)". It may be worthwhile sometime in the future to figure how to package our plugin as one, but for now I think it's best to just focus on getting something that is able to be developed/tested.

> Is it feasible to do a manual override for this? As in, could we set `GI_TYPELIB_PATH` and `LD_LIBRARY_PATH` before loading `gi` in our environment? This seemed to work on my end.
>
I wasn't sure what the ramifications were of manually overriding `GI_TYPELIB_PATH` and `LD_LIBRARY_PATH` in regards to other typelibs, so I dug into the [docs](https://lazka.github.io/pgi-docs/GIRepository-2.0/classes/Repository.html) and found:
```
GIRepository.Repository.prepend_search_path()
GIRepository.Repository.prepend_library_path()
```
After adding these to `pictonode.py` with a quick `GtkNodes.NodeView()` it's all dandy on my end as well and we now have access to GtkNodes at plugin runtime.

#43 includes an install script that _should_ work with a non-superuser/root run of flatpak GIMP, as well as the changes to `pictonode.py`
