### ISSUE TITLE
Tracking issue for features beyond base functionality

### ISSUE THREAD

**Issue by notgull** [notgull/pictonode#67]
In the wake of #23, we have a decently stable web-and-GIMP-plugin setup that should serve as a good base for adding additional features. I've added a handful of issues that should give us stuff to do beyond the current alpha.

## High Priority

- [ ] Fix current web view bugs (#61)
- [ ] Add expected features to web node review (#62)
- [ ] Add saving/loading to pipelines (#64)
- [ ] Add user accounts (#65)
- [ ] Store projects on the backend
- [ ] Deploy the newest setup to `pictonode.com` (cc @meredith-grace)

## Low Priority

- [ ] Add a function for formatting the tree (#63)
- [ ] Add more nodes (#66)

(Feel free to add more)
